### ISSUE TITLE
This is awesome thank you!

### ISSUE THREAD

**Issue by teddybear082** [christinoleo/FollowBone3D#2]
I know this isn’t really an issue so you can close it but just wanted to say your plugin is making it so easy for me to make enemies that can melee the player with punch animations.  I am also in the process of trying to use it to make quasi-physics based hands in VR and so far it is going really well.  Thank you very much for taking the time and effort to make this public and free!

**Comment by christinoleo** [comment]
Hey! Thanks very much for your "issue"! I'm very glad that this thing I made has been in any way helpful to you, and even more glad to receive such a comment at my birthday, so double thanks 😄
